//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitOfWork {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitOfWork.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Return code: {1}.
        /// </summary>
        internal static string CallReturnCode {
            get {
                return ResourceManager.GetString("CallReturnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to GetAll() returned: {0}.
        /// </summary>
        internal static string CallToGetAllReturned {
            get {
                return ResourceManager.GetString("CallToGetAllReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q: Quit application.
        /// </summary>
        internal static string Enter_Q_to_quit {
            get {
                return ResourceManager.GetString("Enter_Q_to_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to start app..
        /// </summary>
        internal static string EnterToStart {
            get {
                return ResourceManager.GetString("EnterToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to continue.
        /// </summary>
        internal static string EnterToTerminate {
            get {
                return ResourceManager.GetString("EnterToTerminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1: Basic BeginTransaction.
        /// </summary>
        internal static string Menu_Option_1 {
            get {
                return ResourceManager.GetString("Menu_Option_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2: Intermediate (Settings) BeginTransaction.
        /// </summary>
        internal static string Menu_Option_2 {
            get {
                return ResourceManager.GetString("Menu_Option_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3: Full (Archive) BeginTransaction.
        /// </summary>
        internal static string Menu_Option_3 {
            get {
                return ResourceManager.GetString("Menu_Option_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select option: .
        /// </summary>
        internal static string Menu_Select_option {
            get {
                return ResourceManager.GetString("Menu_Select_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Patterns: Unit Of Work, Testing application.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------------------.
        /// </summary>
        internal static string ProgramUnderline {
            get {
                return ResourceManager.GetString("ProgramUnderline", resourceCulture);
            }
        }
    }
}
